### ISSUE TITLE
Add dev branch, begin tagging versions, create version milestones to attach issues to

### ISSUE THREAD

**Issue by joslarson** [teotigraphix/Framework4Bitwig#101]
Can we restructure this repo slightly to enable an easier contribution flow. I like having the master be the currently released version and a dev branch be the upcoming release that we can accept pull requests on, but I'm open to other configurations.

Also can we begin tagging the versions of the framework so that those using it can easily find the version they're on for a project. And with that create a milsetone to connect issues to for upcoming releases.

**Comment by git-moss** [comment]
I was not aware that someone else is looking at this repo besides teotigraphix ;-)
Thanks for your suggestions, it makes sense to do that. Therefore, I created a first official release (about time to do that :-)) and a development branch.

**Comment by git-moss** [comment]
I tried to check-in my latest changes to the develop branch but could only select the master. Do I have to check out the develop branch to check-in to that one or how does that work?

**Comment by teotigraphix** [comment]
You have to check out the develop branch on your dev computer, then push to develop after commits.

When you are writing code make sure you have switched branches to develop before you commit, or it will be on master.

**Comment by teotigraphix** [comment]
Once we want a release, we would switch to master on the dev computer, merge develop into master and then push master and tag it. Then you would just switch branches back to develop for more work.

**Comment by git-moss** [comment]
OK, thanks.

**Comment by joslarson** [comment]
Thanks for doing this guys. I'm still just trying to figure out how the framework works to use it in some of my projects. I'll try documenting any confusion I encounter along the way to hopefully contribute some getting started documentation in the future. And if I end up using it a lot, I'm sure I'll have a few things to contribute as well.

**Comment by teotidev** [comment]
@joslarson I was in the process of documenting and making a tutorial project perse' but I have been working on some of my mobile apps and trying to get Touch4Bitwig working with 1.3

If you have any questions, post them here and I can answer them and then close the issue.

**Comment by teotigraphix** [comment]
@joslarson I was in the process of documenting and making a tutorial project perse' but I have been working on some of my mobile apps and trying to get Touch4Bitwig working with 1.3

If you have any questions, post them here and I can answer them and then close the issue.
