### ISSUE TITLE
selectStepContents broken

### ISSUE THREAD

**Issue by fappaas** [teotigraphix/Framework4Bitwig#102]
selectStepContents doesn't work with all notes. 

for (i = 0; i < 127; i++) {
            for (x = 0; x < 127; x++) {
        selectedClip.selectStepContents(i,x,false);
        }
}

**Comment by git-moss** [comment]
Hmm, I cannot get selected anything at all but could create a lot of crashes with 1.3.8 RC 2.

For testing add the following function to Push4Bitwig and call it from the console:

function testScroll ()
{
    var selectedClip = controller.surface.getView (VIEW_SEQUENCER).clip.clip;
    
    for (x = 0; x < 10; x++)
    {
        for (y = 0; y < 127; y++)
        {
            selectedClip.selectStepContents (x, y, false);
        }
    }
};

**Comment by git-moss** [comment]
Crashes Alpha 7 (test from the Console):

clip = host.createCursorClip (8, 8);

function selectNotes ()
{
    for (x = 0; x < 10; x++)
    {
        for (y = 0; y < 127; y++)
        {
            clip.selectStepContents (x, y, false);
        }
    }
};

**Comment by git-moss** [comment]
Fixed in Beta 4.
