### ISSUE TITLE
Closing of Bitwig must wait till function exit () has finished

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#104]
The exit function is not executed or only partly executed.
Also midi devices and IP interfaces must be available during this process so that the external controllers can be shutdown properly.

**Note: This works totally fine when you deactivate the extension in the settings. The problem occurs only when closing Bitwig.**

**Comment by git-moss** [comment]
Still in 1.3.8 RC 2.

**Comment by git-moss** [comment]
Still in 1.3.15 and Alpha 7.

**Comment by nickallen74** [comment]
Can you test if this is still a problem in the build I sent you last night?

**Comment by git-moss** [comment]
Will test later. A good indicator is if all lights on the Push turn off. Is that the case for you?

**Comment by nickallen74** [comment]
When I shut the app down that happens for me.

**Comment by git-moss** [comment]
It works much better now but I am not quite sure if it is fully fixed. The thing is, it happens now only with the Push 2. When I run only the Push 2 all lights are going off. When I add the Push 1, sometimes 2-3 button on Push 2 lights stay on. The more Controllers I turn on (APC, Launchpad) the more button lights on Push 2 stay on, but all other contrllers turn fully off.

**Comment by git-moss** [comment]
Flushing midi messages before closing will be fixed in next update.

TODO : Also fix OSC

**Comment by git-moss** [comment]
Looks good in 2.4 except OSC (e.g., required for disconnecting from the NI hardware service).

**Comment by git-moss** [comment]
Still only working randomly in 3.1.

**Comment by Jengamon** [comment]
It seems to be caused by some kind of buffering, as in my script https://github.com/Jengamon/Launchpad-X-Bitwig-Script/tree/0038bf0856e5845ab3b7c54ba8649c0971699943/session.js#L63#L75 by repeatedly calling "MidiOut.sendMidi" with some trash values, I get it to work pretty well.

But an actual solution would be nice~

**Comment by git-moss** [comment]
Seems to work fine by now.
