### ISSUE TITLE
Settings are reset to 0 when song is closed

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#107]
On Linux Bitwig sets all settings to zero when a song is closed (before setting them again to their previous value). This can create script errors when 0 is out of the range of the setting.
I had the issue with an UDP port configuration (push 2 display communication). The port was set to 0 and an message was tried to be sent which crashed the script.
This does not happen on Windows.

**Comment by nickallen74** [comment]
I think this one should be fixed now.

**Comment by git-moss** [comment]
Fixed in Beta 5.
