### ISSUE TITLE
Triplets are too long when set with Clip.toggleStep

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#108]
When sequencing notes with toggleStep and the grid is set to triplets every 2nd note covers 2 steps but should cover only 1. (You can test with Push4Bitwig sequencer).

**Comment by git-moss** [comment]
Still in 1.3.8 RC 2.

**Comment by git-moss** [comment]
Still in 1.3.15 and Alpha 7.

**Comment by goofymongol** [comment]
I need this fixed @teotigraphix !! It's very important, otherwise I can't properly program beats with my push :(. @git-moss Is there no other way to program this? toggleStep.setlenght or something?

**Comment by git-moss** [comment]
It is correct how it works now. It covers 2 steps when the note "reaches" into them.
