### ISSUE TITLE
1.3.6 Windows installer is missing the API documentation

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#110]
Don't know about the other OSs.

**Comment by karshan** [comment]
I noticed this too, it isn't missing for the linux version

**Comment by git-moss** [comment]
Still in 1.3.8 RC1

**Comment by git-moss** [comment]
Fixed in 1.3.8 RC2.

**Comment by git-moss** [comment]
Actually, the HTML files are there again but the inheritance graph images are still missing...

**Comment by git-moss** [comment]
Still missing in 1.3.8 RC 3.

**Comment by git-moss** [comment]
Still missing in 1.3.8 RC 4.

**Comment by git-moss** [comment]
Fixed in 1.3.8.
