### ISSUE TITLE
Crashes navigating layers and devices

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#111]
From the forum:
http://www.kvraudio.com/forum/viewtopic.php?f=268&t=409982&p=6390713#p6390713

First FX layer:
Make fxlayer... put 2 native BWS fx in it.
Dive in... and overhere i cant select the fx with the buttons on the push-1.
You can select them with mouse and you,ll see them get selected aswell on push screen.
But then select a fx->dive into it-> and dive :scared: out. BOEM crash.(most often it happens right away, sometimes after a couple of times selecting it and dive in and out)
Sometimes it looks like it doesnt "catch" back the fx in it or something.
But when it doesn,t happen .... add a 3rd native FX in it and dive in, and again out, it happens right away for sure.
Before this 1.3.8 update my push screen just freezes, what doesn,t happen anymore with this update.
But it doesnt let me go out the fx. (before i couldnt get in :o :hihi: )

Drumlayers:
When auto select drums , set to: channel.... (beautiful update btw! :tu: :tu: )
Also.... :? it doesn,t happens everytime. :scared:
But when i drop a breakbeat on a pad and copy them to other pads, to break it into sections.
And when i dive into a pad, and THEN slap another pad (without getting out) it selects another pad. (what it mostly does and your back to the top layer of that pad)
But sometimes it loses focus or something, and it doesnt gets out of the a pad, but you can go to TRACK and select tracks,or clips in SESSION, but when coming back to the drummaschine with the problem,
And dive in and out it crashes BWS.
Or when you stay on that drummaschine and you force to get out with the arrow buttons it crashes also.

**Comment by vosc** [comment]
The first one should be fixed in the next update (1.3.8 RC-2), works fine for me now.

The second one i did not understand. What is "auto-select drums"? I don't know Push4Bitwig too well and did not find that feature in the latest version.

**Comment by git-moss** [comment]
Enable "Auto-Select drum channel" in the script properties (Under the "Workflow" section). Then when you select the different pads in the drum sequencer the channel of the pad should be selected automatically in the display.

**Comment by git-moss** [comment]
The crashes are fixed in 1.3.8 RC 2 but there are 2 new bugs now:
https://github.com/teotigraphix/Framework4Bitwig/issues/113
https://github.com/teotigraphix/Framework4Bitwig/issues/114
However, closing this one.
