### ISSUE TITLE
Selecting instrument layers broken

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#114]
1) Add an instrument layer device
2) Add two layers
3) Try to select them with a controller  (layerBank.getChannel (index).selectInEditor ();)
-> Nothing happens

Since 1.3.8 RC 2 ?! (works fine in 1.3.6)

**Comment by vosc** [comment]
Should be fixed in 1.3.8 RC-3.

**Comment by git-moss** [comment]
Fixed in 1.3.8 RC-3.
