### ISSUE TITLE
Sequencers are not working if tablet display is active

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#117]

**Comment by vosc** [comment]
I don't understand, what means "sequencers are not working"?

**Comment by git-moss** [comment]
It means that the steps are not sent anymore, therefore the sequencers do nothing. E.g. test with note sequencer, drum sequencer or raindrop sequencer on Push.

**Comment by git-moss** [comment]
To clarify further: With "table display" I mean the specific Bitwig view for touch.

**Comment by git-moss** [comment]
Fixed.
