### ISSUE TITLE
Add a setting for the piano orientation

### ISSUE THREAD

**Issue by abique** [teotigraphix/Framework4Bitwig#120]
Hi, I think it would be easier to have a setting for the orientation: horizontal/vertical instead of many names with ^ or >.

What do you think?

**Comment by git-moss** [comment]
I think that the symbols are easier to see if you want to pick it quickly. Furthermore, the "horizontal/vertical" texts would need to be abbreviated.

**Comment by abique** [comment]
I meant have a boolean setting for the piano orientation, not replace the > and ^ characters by a long word ;-)

**Comment by git-moss** [comment]
Ah, that makes sense. :-)

**Comment by git-moss** [comment]
Done.
