### ISSUE TITLE
Track: enter/exit group track to set document scope

### ISSUE THREAD

**Issue by joslarson** [teotigraphix/Framework4Bitwig#127]
Currently, the api does not expose the ability to enter or exit a track group, or in anyway change the document scope, as is currently possible only by right clicking on track and selecting "Enter Group" or selecting from the document scope dropdown (see below).

Could be attributes of Track.

I'm suggesting this be added under the labels `bitwig-improve`, `1.3.x`, and `important`.

![image](https://cloud.githubusercontent.com/assets/3181232/19821752/555535aa-9d1d-11e6-8db2-7cf1c59e5783.png)

![image](https://cloud.githubusercontent.com/assets/3181232/19821731/3d531562-9d1d-11e6-9a25-0a658145e5b2.png)

**Comment by git-moss** [comment]
That's already possible but not so obvious. Look at the functions TrackBankProxy.selectChildren and TrackBankProxy.selectParent in the Framework.

**Comment by joslarson** [comment]
@git-moss Thanks for the reply :) Either I don't completely understand your code, or you didn't quite understand my issue. In bitwig if you right click on a group track and choose "Enter Group" (give it a try) that group track becomes the master track and it's children become the top level tracks, such that the rest of the project is completely out of scope and is not even triggered when triggering full scenes.

Your code seems to successfully select the parent or child track, but it does not change the actual visible scope of the bitwig document in the software. In fact if I manually narrow the scope (by right clicking and selecting "Enter Group" from the menu), calling `cursorTrack.selectParent()` will not climb up beyond the scope I am currently at.

What I'd like is if I could call `cursorTrack.enter` to narrow the document scope or `cursortrack.exit` to open it back up. It would also be nice to be able to programmatically look at the entire tree from any scope so that we could change the scope up or down more than one level.

I have emailed bitwig with this feature request and they told me this feature is not yet accessible in the API, so I thought this would be a good place to submit the issue for tracking.

**Comment by abique** [comment]
I already added two functions to the control surface api, which lets you enter/leave group track as if you did it from the GUI. So it is in a development branch, it might show up in the future.

**Comment by joslarson** [comment]
Thanks @abique, that one feature alone will be a big deal for me.

**Comment by git-moss** [comment]
Great.

**Comment by joslarson** [comment]
@abique did this make it into the beta? I don't see it, but I'm wondering if it's just currently undocumented?

**Comment by abique** [comment]
@joslarson Application.navigateIntoTrackGroup()/navigateToParentTrackGroup()

**Comment by git-moss** [comment]
Please add to the API documentation.

**Comment by abique** [comment]
It is already in the generated documentation

**Comment by git-moss** [comment]
You are right! I did not notice it because the "since" flag is missing, maybe you can add that, too.

**Comment by abique** [comment]
OK! :)

**Comment by joslarson** [comment]
@abique I tested these out tonight, and it looks like `Application.navigateIntoTrackGroup(track)` does nothing (I'm running Beta 2), and `navigateToParentTrackGroup()` works sometimes, but seemingly randomly jumps to the project root, skipping the parent track group it should navigate to.

**Comment by git-moss** [comment]
I guess that's a side effect of these bugs: https://github.com/teotigraphix/Framework4Bitwig/issues/133
