### ISSUE TITLE
Group, layer and device navigation broken (regression)

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#133]
Quite some regressions here:

1) Selecting a group enters it (but should only select it)
2) Cannot leave group
3) Layers cannot be selected
4) Devices cannot be selected
5) No device is selected when changing a track
6) Sampler cannot be entered from drum device
7) Siblingsbank no longer adjusted when track outside its bank is selected in Bitwig

Test with Push4Bitwig.

#4 is broken in function:
CursorDeviceProxy.prototype.selectSibling = function (index)
{
    this.cursorDevice.selectDevice (this.siblings.getDevice (index));
};

**Comment by nickallen74** [comment]
This should be fixed in beta 4 (or the build I send you tonight).

**Comment by git-moss** [comment]
Not sure about #5. I had to select a device on the 2nd track first, when then changed it works.
All other bugs are fixed!

**Comment by git-moss** [comment]
Closing and moving 5) to here: https://github.com/teotigraphix/Framework4Bitwig/issues/160
