### ISSUE TITLE
Option to delay loading of plugins when scrolling through presets in browser

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#143]
Scrolling through the presets is a bit jumpy since there are delays when a different plugin is loaded. It would be nice to have an option to wait for some millis so the preset gets only loaded when the user "rests" on it for a bit.

**Comment by nickallen74** [comment]
There is already a delay in place. Do you have the problem if you press and hold arrow down for example? It should all use the same delay mechanism but maybe it is not always working when coming from a controller. I will investigate a bit...

**Comment by git-moss** [comment]
I always scroll with the knob. This leads very quickly to a big loading mess and hangs for seconds.

**Comment by nickallen74** [comment]
Ok should be fixed in the next build.

**Comment by git-moss** [comment]
In which way? Is there an option or did you increase the delay time?

**Comment by git-moss** [comment]
Fixed.
