### ISSUE TITLE
Drum pad colors not sent (regression)

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#144]

**Comment by NickJAllen** [comment]
I hope this one is also fixed in the next update but haven't tested it myself as unsure how to...

**Comment by teotigraphix** [comment]
@NickJAllen  Hook me up with the alpha, I know how to test this on the Push. :)

**Comment by git-moss** [comment]
To test:
1) Create a track with a drum instrument and load a drum kit
2) On the Push press "Note" and then select "Drum"
3) The pads in the lower left corner should now show the colors of the track (if they have no individual assignments)
4) Test if the colors update if you change the track color and/or change the color of an individual pad.

**Comment by NickJAllen** [comment]
Ok thanks for the steps. Seems to work for me in my latest build.

**Comment by git-moss** [comment]
Fixed.
