### ISSUE TITLE
Transport.setLauncherOverdub broken (regression)

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#145]

**Comment by git-moss** [comment]
Still in Beta 2.

**Comment by nickallen74** [comment]
Is this fixed in beta 3? I think it could be because I changed some stuff related to that.

**Comment by git-moss** [comment]
It's not fixed in 50757. To test simply press the New button (on Push) on a track.

**Comment by nickallen74** [comment]
How can I tell if it's worknig? It seems to do what it should on our side.

**Comment by git-moss** [comment]
Press the New button on the Push. This creates a clip, starts it and activates overdub.

**Comment by NickJAllen** [comment]
This seems to be caused by inverting the on/off in transport proxy in the git version:

TransportProxy.prototype.setLauncherOverdub = function (on)
{
    // Note: This is a bug: On and off are switched
    this.transport.setLauncherOverdub (!on);
};

If I make it send the actual value it works for me.

**Comment by git-moss** [comment]
Ah, I did not look in the Framework code. So, you actually fixed the function, which was broken :-)
I am wondering if it would be better to keep this function in its broken state (to be backwards compatible) but deprecate it. I can switch to the Value implementation isClipLauncherOverdubEnabled to have clean code.

**Comment by NickJAllen** [comment]
It seems in the original Push script though that this inversion was not 
done. So not sure when or why you did the bool inversion. If it was only 
a bug because of the 2.0 Alpha/Beta phase then it would make sense to 
not invert it at all.


Nick

**Comment by git-moss** [comment]
1.3.15 needs that inversion.

**Comment by NickJAllen** [comment]
Maybe you can just do the inversion if the host version matches that? 
You can check that with Host.getHostVersion(). I think that's better 
than inverting it for all the versions where it works correctly.


Nick

**Comment by git-moss** [comment]
I only update to the latest version. So, let's close this.
