### ISSUE TITLE
Harmonize ClipLauncherSlot and Clip

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#146]
You can set the name of a clip (Clip.setName) but there is no function to monitor it.
It would be nice to have the same interface for Clip and ClipLauncherSlotBank (like ChannelBank and getChannel -> Channel).
If the idea is that a Slot contains a Clip then there should be a getter, otherwise the same Classes should be used.

**Comment by abique** [comment]
Might sound strange, but the slot selection and clip selection are disconnected.
You can have a clip selected and visible in the clip editor, while an empty slot is selected as well.

The right way would be Clip.clipLauncherSlot() or Clip.sceneIndex().
