### ISSUE TITLE
Parameter.modulatedValue does not match Parameter.value for non-continuous values

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#151]
A parameters modulated value is identical to the value if not modulated. For non-continuous parameters like the filter type of Polysynth or the delay time (in note lengths) of a delay this shows strange effects.

To test simply print out the values and compare.

**Comment by NickJAllen** [comment]
I don't really understand. The modulated value has to be the same as the value if it is not modulated. What else should it be?

**Comment by git-moss** [comment]
Yes, they should be the same! But that is not the case for the parameters noted above!

**Comment by nickallen74** [comment]
Oh that was a silly one. Nothing to do with the controllers. It was wrong on the app/engine side. Fixed for next build though.

**Comment by git-moss** [comment]
#105 is closely related to that one.

**Comment by git-moss** [comment]
Fixed.
