### ISSUE TITLE
Transport.getPosition ().addTimeObserver (":", 3, 2, 2, 2, ...) does not update (regression)

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#152]
Only fires once. Calling transport.getPosition ().addValueObserver or markInterested makes it work.

transport.getPosition ().addValueObserver does not receive a value.

**Comment by nickallen74** [comment]
Should be fixed in next build.

**Comment by git-moss** [comment]
Fixed in Beta 2.
