### ISSUE TITLE
DrumPadBank.scrollChannelsDown / scrollChannelsUp broken (regression)

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#157]
- scrollChannelsDown does nothing 
- scrollChannelsUp scrolls a full channel page

**Comment by git-moss** [comment]
scrollChannelsDown is fixed.

**Comment by NickJAllen** [comment]
Oops seems like scrollChannelsUp was trying to scroll by pages. Copy and paste error. Hopefully fixed in the next build.

**Comment by git-moss** [comment]
Fixed.
