### ISSUE TITLE
Selected device does not automatically display its 1st parameter page (regression)

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#158]

**Comment by NickJAllen** [comment]
Should be fixed in our next official build.

**Comment by git-moss** [comment]
Don't see a change in your preview version.

**Comment by NickJAllen** [comment]
Maybe I misunderstood this bug report. But the bug I fixed is that there is always a remote controls page selected in a device and opening projects from old versions should select the first preset page. I could reproduce this problem and now when I use Push there is a page selected when I go to a device. What should I do to reproduce?

**Comment by git-moss** [comment]
Hmm, maybe this is a specific problem of my setup:

 I have a simple template (stored with a 1.x version), which I automatically open at startup. It contains only 1 track with a Polysynth. When I switch to Device after such a startup it has no Page selected.
[JMsTemplate.zip](https://github.com/teotigraphix/Framework4Bitwig/files/793700/JMsTemplate.zip)

**Comment by NickJAllen** [comment]
I will test it with that template and let you know...

**Comment by NickJAllen** [comment]
Ok I can reproduce with that template. Will hopefully have a fix soon.

**Comment by nickallen74** [comment]
Should be fixed in beta 5.

**Comment by git-moss** [comment]
Hooray, fixed :-)
