### ISSUE TITLE
No cursor device selected when project is opened (regression)

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#160]
When you open a project there is a selected track but NO selected cursor device. Therefore, one always has to click with the mouse on a device. Please automatically select the first device of the selected track.

**Comment by git-moss** [comment]
For 2.0 Beta X it seems you have to select it now once for each track.

**Comment by nickallen74** [comment]
This should be fixed in next build.

**Comment by git-moss** [comment]
Fixed.
