### ISSUE TITLE
Wrong deprecation comment for Device.isMacroSectionVisible and isParameterPageSectionVisible

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#165]
It says "Use #getAreRemoteControlsVisible() instead" but it must reference: isRemoteControlsSectionVisible()

**Comment by nickallen74** [comment]
Fixed.

**Comment by git-moss** [comment]
Half fixed :-)
Still with isParameterPageSectionVisible ().

**Comment by NickJAllen** [comment]
Fixed
