### ISSUE TITLE
Device.modulatedValue() has a setter but should not

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#168]
It also says in the documentation that it is readonly (RangedValue).

**Comment by NickJAllen** [comment]
Our private implementation does indeed include a setter. But this is not exposed via the API and should not be used. I understand you can bypass that by using non type safe scripting language. I'll see if there's an option that prevents that from happenning and only using the public interface.

**Comment by git-moss** [comment]
Hmm, but that is not the case for the other readonly Values. Does their internal-setter have a different name?

**Comment by nickallen74** [comment]
The setter exists in the implementation but it will do nothing if you call it and it is not settable.

**Comment by git-moss** [comment]
That raises the question why it is there at all?
OK, you're the boss, if you want to keep it so be it. :-)
