### ISSUE TITLE
Sending clip names broken

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#178]
Names of clips are not sent:

tracks = host.createMainTrackBank(1,5,5);
tracks.getTrack(0).getClipLauncher().addNameObserver(function(i,name) {
     println(i,name);    // Always empty
});

**Comment by git-moss** [comment]
Testscript for API 3:
--- snip -------

loadAPI(3);

host.defineController("moss", "TestClipNames", "0.1", "2aba2a20-297c-4da7-b5e5-7413728cfca2", "moss");

function init()
{
    tracks = host.createMainTrackBank(1,5,5);
    tracks.getChannel (0).clipLauncherSlotBank ().addNameObserver (function(i,name)
    {
        println(i + ": " + name); // name is always empty
    });
}

**Comment by weasei** [comment]
I'm also fighting with this bug - Bitwig support keeps telling me this:

> as stated in the previous, getting the name is possible via ClipLauncherSlotOrScene and you're using ClipLauncherSlotBank.

In my opinion this doesn't make any sense and I couldn't get it to work. 
I've also tried it like this:
trackBank.getChannel(0).clipLauncherSlotBank().getItemAt(0).name().toString()
to get the name of the Clipslot 0 of Track 0. No success.

**Comment by teotigraphix** [comment]
@git-moss What is the API 3? When did/is it chaining?

**Comment by git-moss** [comment]
API 3 was introduced in a 2.1.x (not sure in which exactly). Just look at the API history of 2.1.4.

**Comment by teotigraphix** [comment]
Yeah thanks, I just noticed it in the history. 

I guess they are changing version conventions then. That was really what I was wondering.

**Comment by git-moss** [comment]
@weasei Who did answer that to you? AFAIK ClipLauncherSlotOrScene can only be retrieved for scenes.

**Comment by git-moss** [comment]
In case you did not read that: The API version numbering is now independent from the Bitwig Studio numbering.
 
Von: Michael Schmalle [mailto:notifications@github.com] 
Gesendet: Freitag, 29. September 2017 22:24
An: teotigraphix/Framework4Bitwig <Framework4Bitwig@noreply.github.com>
Cc: Jürgen Moßgraber <juergen.mossgraber@googlemail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [teotigraphix/Framework4Bitwig] Sending clip names broken (#178)
 
Yeah thanks, I just noticed it in the history.
I guess they are changing version conversions then. That was really what I was wondering.

**Comment by teotigraphix** [comment]
eh... I meant "version conventions", must be changing the version with point releases now.

**Comment by weasei** [comment]
@git-moss the answer came from the Bitwig Technical Support Team. I got quite frustrated as I couldn't convince them it's a problem as they repeatedly stated this.

**Comment by git-moss** [comment]
Fixed in 2.2.3 RC1.
