### ISSUE TITLE
Plan for updating deprecated methods

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/Framework4Bitwig#181]
I'm going through the framework now and developing T4B.

I need to get back on track with what your plans are with the refactoring for 2.0.

Case in point, I am interested in adding Clip messages to my OSC fork that I use and I noticed that say;

```
In CursorClipProxy ...

Host.createCursorClip()
```
is deprecated and uses launcher/arranger specific methods.

So I was wondering how you are attacking this stuff, should I just create an issue when I run into this stuff so we can talk about it?

**Comment by git-moss** [comment]
Please create individual entries.
