### ISSUE TITLE
CursorDeviceLayer hasNext and hasPrevious are always false

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#182]
this.cursorDeviceLayer = this.cursorDevice.createCursorLayer ();
this.cursorDeviceLayer.hasPrevious ().get ();
this.cursorDeviceLayer.hasNext ().get ();

**Comment by NickJAllen** [comment]
I think this should now be fixed but it's not in the beta 3 I sent you.

**Comment by abique** [comment]
Is it so?

**Comment by git-moss** [comment]
Yes, fixed.
