### ISSUE TITLE
RemoteControls.selectedPageIndex ().set (index) always selects items on 1st page

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#183]
Test with Push4Bitwig 9 Beta 1 (Java)
1) Select a device with more than 8 parameter banks.
2) Scroll to a bank > 8 with the cursor right key
3) Directly select a bank (pressing a 1st row button)
-> The selection jumps to the 1st bank page

**Comment by NickJAllen** [comment]
I don't think this is a bug on our side. The index is an index into the pageNames array which is always the complete list of page names (it's not a bank). So the offset must be specified and ignored somewhere in the Push code...
