### ISSUE TITLE
Implement "bank page follows selection" for browser filters and results

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#184]

**Comment by NickJAllen** [comment]
do you use CursorBrowserItem.createSiblingsBank to create the banks?
If so that one should always follow the cursor
If you use BrowserColumn.createItemBank it won't
I think the last one we should deprecate and remove
can't think why anyone wants to create a bank that does not follow the cursor

**Comment by git-moss** [comment]
Works fine with siblings bank.
