### ISSUE TITLE
Wrong formatting of Extension names

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#186]
I am not quite sure what the logic is to display them in the “add manual” menu. With P4B the author appears but not with AutoColor. Also there is a space missing between the extension name and the author. With P4B there is the hardware model missing.
I would suggest to do (for the new Java extensions):

“Hardware Vendor” -> “Hardware model (Script name – Author)”
![scripts](https://cloud.githubusercontent.com/assets/3090132/24838623/b144af04-1d4b-11e7-989a-f26c2d5c1f00.png)
![scripts2](https://cloud.githubusercontent.com/assets/3090132/24838624/b1a8d646-1d4b-11e7-82b8-d9be79257a02.png)

**Comment by NickJAllen** [comment]
This should be fixed in the next update.
