### ISSUE TITLE
Arranger - API to Show/Hide Deactivated tracks.

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/Framework4Bitwig#199]
I had this a year or so ago mixed with effect visible.

As far as I can see, there is no way to toggle Deactivated tracks.

![adwe123123](https://user-images.githubusercontent.com/226417/31126016-62d3fc32-a818-11e7-804a-b8bcc4d548e4.PNG)

**Comment by git-moss** [comment]
Implemented in API 11.
