### ISSUE TITLE
Don't adjust track bank to upper bound

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#202]
Test with any 8 track controller script (e.g. Push4Bitwig):
1) Create 9 tracks
2) Tracks 1-8 are displayed
3) Switch bank upward (Shift+Cursor right)
4) Tracks 2-9 are displayed and track 2 is selected
Before only track 9 was displayed and selected (this is what you want). Also this offset is pretty confusing when you have multiple banks and go down the tracks again.

**Comment by git-moss** [comment]
This seems to be a problem of all bank types (e.g. browser filters and presets).

**Comment by nickallen74** [comment]
Should be fixed in 2.3 Beta 2. let me know if there are still problems.

**Comment by git-moss** [comment]
Fixed.
