### ISSUE TITLE
Directly send current setting values on init (instead of default values)

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#208]

**Comment by Skrappjaw** [comment]
Even if the ports cant be set, can the IP?

**Comment by git-moss** [comment]
The problem exists with all properties/values you need to set in the init function.

**Comment by Skrappjaw** [comment]
ok. a work around might be to setup ip forwarding. I'm using touch osc and need the feedback to the tablet.

**Comment by git-moss** [comment]
The correct settings are sent since Bitwig 3.1.
