### ISSUE TITLE
Clip.toggleStep  off by 3 octaves

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#211]
I got a bug report from a user and have no idea what is the problem:
The note sequencer on the Push (also on other devices, which use the same code) is off by 3 octaves but it works correctly on the Raindrop sequencer.

The note sequencer calls:
	clip.toggleStep (step, row, velocity);
The raindrop sequencer uses:
	clip.setStep (step, row, velocity, duration);
Therefore, I first suspected the toggleStep function but replacing it with clearStep/setStep showed the same effect.

When setStep (0,36) is called from Raindrop it correctly creates a C1 but when called from NoteSequencer it creates a C4.
The sequencers use different CursorClip instances (one with 8x128 and one with 512x128).

I tried to replicate the problem with a short JavaScript extension but there it works correctly.

To replicate:
1) Start Push
2) Create and select a clip
3) Enter Note sequencer (Press "Note" + select "Sequencer")
4) Press the lowest left pad on the grid. This should create a C1 note on the first step of the clip but creates a C4.
[5) On the Raindrop sequencer also press the lowest left pad on the grid, which correctly creates multiple C1 notes]
 
Tested with latest 2.3.5 (also in 2.4).

**Comment by git-moss** [comment]
Some more debugging:

The results from this.clip.addStepDataObserver (this::handleStepData) first send the correct note to the callback then 3 times a note 3 octaves higher:

(col:row:state)
0:36:2
0:72:2
0:72:2
0:72:2

0:48:2
0:84:2
0:84:2
0:84:2

0:52:2
0:88:2
0:88:2
0:88:2

**Comment by git-moss** [comment]
Seems the problem is that addStepDataObserver registers all obervers for clips with the same number of rows together. Since I create 4 clips with different step numbers but the same amount of rows my callback gets called 4 times. These clips are used for different sequencers and have different octave setups, so this creates a mess.

**Comment by git-moss** [comment]
Seems to be fixed in Beta 3.

**Comment by git-moss** [comment]
Happening again in Beta 4.

**Comment by nickallen74** [comment]
The problem is that you are calling scrollToKey(36) which sets the new base key in one of your clips you create. This is what causes the key to be inserted in the wrong place. I've improved the documentation but the actual fix needs to be on your side to not call scrollToKey if you don't want to.
