### ISSUE TITLE
NoteInput.sendRawMidiEvent ignores midi channel

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#224]
All midi messages are on midi channel 1. Since midi channels are supported since Bitwig 2.4 this function should be updated as well.

**Comment by vosc** [comment]
Should be fixed in the upcoming 2.5 beta-5.

**Comment by git-moss** [comment]
Now it does not work at all. Is this related to this: "Prevent control surfaces from sending MIDI system messages via MidiOut.sendMidi() which is intended for channel messages" ?!

**Comment by abique** [comment]
Fixed for 2.5 beta 6.

**Comment by git-moss** [comment]
Works fine now!
