### ISSUE TITLE
Bank.scrollIntoView does not work / or add Bank.makePageVisible()

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#225]
Tested with TrackBank and SceneBank to scroll the clip view but nothing happens.

**Comment by nickallen74** [comment]
This method seems to work fine. The problem appears to be in the Push 2 extension. It calls the scrollIntoView method but very soon after calls the scrollTo with an absolute position that overrides the scrollIntoView.

**Comment by git-moss** [comment]
Add a new method to Bank to make the current page visible in the Bitwig UI, e.g.:
Bank.makePageVisible()

**Comment by git-moss** [comment]
It is still not working in 3.1.
If scrollIntoView is not intended to make the track/scene visible in Bitwig (as it says in the API documentation), then we need something like Bank.makePageVisible().
**The problem with this is that in the Session View you cannot see the selection area anymore and get totally lost.**

**Comment by dplduffy** [comment]
Will be writing to bitwig on this, but I would also like to have this fixed.  I'm working on a script to control device pages and it really sucks that I can't automatically move the device pane to focus on the current cursor device, having to reach for a mouse is no bueno.

**Comment by git-moss** [comment]
This is addressed in 4.3.
