### ISSUE TITLE
Switching Arpeggiator.mode () causes hanging notes

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#231]
All modes besides All and Up, seem to behave weird and cause hanging notes.

**Comment by abique** [comment]
Fixed for beta 3.
Changing the mode will cause all the notes to stop, and it will reset the octave offset and current note index as well.

**Comment by git-moss** [comment]
Still happens.

**Comment by git-moss** [comment]
I need to rephrase: the notes that hang are not the ones played. When I switch the mode it starts and  keeps playing a low C-2. Just tested with Beta 3.

**Comment by abique** [comment]
I have an additional fix.

**Comment by git-moss** [comment]
Just came to my mind, that this could be the midi note of touching the knob with which I change the mode! Which should be blocked.

**Comment by abique** [comment]
I rewrote how we deal with the octave and founds a few other issues here and there, the next build that you'll try should work better!

**Comment by git-moss** [comment]
Fixed.
