### ISSUE TITLE
NoteStep values not updated in Bitwig UI

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#236]
Changing one of the following values does not update the display in the inspector (you have to switch to another note and back):

setPan (pan:double): void
setPressure (pressure:double): void
setTimbre (timbre:double): void
setTranspose (transpose:double): void
setVolume (volume:double): void

**Comment by git-moss** [comment]
Still in Beta 3.

**Comment by abique** [comment]
Fixed on my dev branch.

**Comment by abique** [comment]
fixed on my branch

**Comment by git-moss** [comment]
Fixed.
