### ISSUE TITLE
NoteStep.volume() issues

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#237]
1) It is settable in the range of 0..1 as said in the docs but it reports its value in the range of 0..2.
2) Also, how can I format this as dB (like in the Bitwig UI)?

**Comment by abique** [comment]
Should be fixed in beta 3, it will use a normalized ranged (0..1) for both input and output :)

**Comment by git-moss** [comment]
1) works fine now
To make 2) work, could this be implemented as a parameter?

**Comment by abique** [comment]
2) is difficult... :'( especially if the range goes higher in the future...

**Comment by git-moss** [comment]
Isn't that the case with all (device) Parameters as well?

**Comment by abique** [comment]
The pan is from -1 to 1, so it is not normalized or it would be 0..1.
I'm not sure what's best.

**Comment by git-moss** [comment]
You can scale any kind of parameter with devices or tracks. Why not with this volume() ?

**Comment by git-moss** [comment]
Seems to stay that way.
