### ISSUE TITLE
Enhancements to Hardware simulation editor

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#240]
1) Use a Monmospace font for the text display

2) No window resize handle on right/bottom corner

3) Font should be scaled to fit the button

4) Textcolor should be the contrast to the background color (e.g. white on green is pretty hard to read)

5) If you simulate a controller and connected the real thing, you need to restart Bitwig to make it work.

**Comment by NickJAllen** [comment]
4 is done by providing the HardwareLightVisualState
5 You should be able to simulate the disconnect instead of restarting the engine but haven't tried

**Comment by git-moss** [comment]
Fixed.
