### ISSUE TITLE
CursorClip Update buggy

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#247]
There is an update bug with CursorClip.addNoteStepObserver (this::handleStepData).
To reproduce use the Push note sequencer:
1) create track
2) create 1bar clip
3) put in notes in note sequencer position 1 and 5 on 1st page
4) witch to second page and put note in position 1
5) position 5 will light up on Push even if there is no note in the corresponding position inside clip.
6) Switch back to page 1, looks good
7) Switch to page 2, also looks good now

Debugging shows that when the note on the 2nd page is created, notes are sent starting from the 1st page (incl. the 2nd).
![CursorClip Update Bug](https://user-images.githubusercontent.com/3090132/71768613-d86d0c80-2f17-11ea-89fd-40adfce7f81f.png)

**Comment by git-moss** [comment]
Still in 3.1.3.

**Comment by abique** [comment]
Hey Moss,
I don't have push, but I have the launchpad pro (mk1).
I've tried your steps with the Bitwig extension and I could not reproduce it.
Could it be a bug in your implementation?

**Comment by git-moss** [comment]
I fixed it by removing the arrangerClip. Not sure why it did not work when we tested it.
