### ISSUE TITLE
Color settings do not fire during start of extension

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#248]
E.g. test with Push 2 color settings.

**Comment by NickJAllen** [comment]
I can't see any problem from our side. The initial value of the setting is the one defined in the prefs for the controller as expected so please be more specific about what the problem is

**Comment by git-moss** [comment]
Instead of adding firing the current value on startup, the value should be retrieved via the getter, which is already possible. Firing of other types will removed.
