### ISSUE TITLE
Cannot turn on audio engine (Application.activateEngine())

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#249]
After the Audio engine has been turned off (Application.deactivateEngine()), it cannot be turned on again (Application.activateEngine()).

The Bitwig log shows the following Exception:

[2020-01-12 10:14:18 ramona-server error] Connection broken with client:
	java.io.EOFException
	at com.bitwig.ramona.serial.bNN.EUM(SourceFile:263)
	at com.bitwig.ramona.serial.bNN.tYM(SourceFile:413)
	at bEY.E3n(SourceFile:847)
	at bEY.EkP(SourceFile:669)
	at bEY.EkP(SourceFile:650)
	at com.bitwig.ramona.protocol.ubZ.EkP(SourceFile:88)
	at bFR.hlF(SourceFile:385)
	at bFT.run(SourceFile:276)

**Comment by NickJAllen** [comment]
I can't reproduce this at all.

**Comment by git-moss** [comment]
Did you try only on Linux?

**Comment by NickJAllen** [comment]
Not necessary to check windows or mac. The API just calls the same thing as when the user clicks does activate / decactivate via the GUI. So I guess there are some problems depending on the audio backend used and audio settings and these problems would also be there for the user doing it via the GUI. Can you confirm this? If so the bug has nothing to do with the API at all. But would still be a serious bug we need much more info on

**Comment by git-moss** [comment]
It happens only via the API.
1) Deactivate via API -> Audio engine is off
2) Activate via API -> Crash
3) Activate via API -> Still crashing
4) Activate via UI -> Crash
5) Activate via UI -> Works again

Will test on Linux tonight.

**Comment by NickJAllen** [comment]
Did you send engine crash reports? I don't see any...

**Comment by git-moss** [comment]
There was no exception in the audio engine log. Seems to be more like a communication problem.

**Comment by NickJAllen** [comment]
The exception is the log is completely harmless and expected

**Comment by git-moss** [comment]
The explanation is that the MIDI processing runs now in the audio thread, which is deactivated after the function call. Therefore, a conceptual problem not a real bug.

**Comment by git-moss** [comment]
Fixed in Bitwig 3.1.3.
