### ISSUE TITLE
User parameters cannot be mapped with OSC (regression in 3.2)

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#256]
Test with DrivenByMoss 9.00 Beta 5 (this the API 11 branch on GitHub).

1) Add DrivenByMoss OSC extension
2) Start Open Stage Control (https://openstagecontrol.ammd.net/), use 0.49.12 not the 1.0 Beta
3) Make sure the in-/output OSC port matches the one in Bitwig
4) Load the Open Stage Control template included in the download (or get it here: https://github.com/git-moss/DrivenByMoss/blob/master/resources/osc/OpenStageControl4Bitwig.json)
5) Select the user parameters tab
6) Enable MIDI mapping in Bitwig
7) Move one of the user parameter faders in the template

Result: nothing happens
Expected: The fader is mapped to the selected parameter

This works fine in 3.1.3. I suspect that it is a side-effect of the Hardware API changes.
The user parameters map fine in the Generic Flexi extension (also part of DrivenByMoss), which does also not use the Hardware API but registers a MIDI callback. I guess that the registering somehow activates the mapping.

**Comment by NickJAllen** [comment]
Should be fixed in 3.2.4 (when released)

**Comment by git-moss** [comment]
Fixed.
