### ISSUE TITLE
JavaDoc errors in API

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#264]
See attached error document. Especially, the "newSince" and "@ @ since" errors should be fixed.
[JavaDocErrors.txt](https://github.com/teotigraphix/Framework4Bitwig/files/5061389/JavaDocErrors.txt)

**Comment by git-moss** [comment]
Source is not publicly available, so cannot check.

**Comment by abique** [comment]
Fixed some of them.
