### ISSUE TITLE
Method to toggle Send on/off

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#287]
Bitwig 4.3 introduces to option to disable sends but a similar method is missing in the API.

**Comment by git-moss** [comment]
"Sends in new projects are now disabled until used (by an initial knob turn or creating automation, etc.)" --> Seems not to be the case via the API.

**Comment by abique** [comment]
Fixed in API version 18

**Comment by git-moss** [comment]
Works fine!
