### ISSUE TITLE
createEffectTrackBank has no paramter for sends

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#290]
Bitwig 4.3 supports to have Sends on FX channels but controllerHost.createEffectTrackBank provides no option to create a sendsBank.

Add a new parameter for the number of sends to support (like with createTrackbank).

**Comment by abique** [comment]
Fixed in API version 18

**Comment by git-moss** [comment]
It is sadly not working. I created a new FX bank with (numSends was set to 2 or 8): 
controllerHost.createEffectTrackBank (numFxTracks, numSends, numScenes);

But it crashes when I try to access one of the send banks of one of the FX channels:

No send bank exists: Requested a send bank size of 0
ANQ: No send bank exists: Requested a send bank size of 0
    at com.bitwig.flt.control_surface.proxy.AbstractChannelProxy.sendBank(SourceFile:207)
    at com.bitwig.flt.control_surface.proxy.AbstractChannelProxy.sendBank(SourceFile:56)

**Comment by git-moss** [comment]
Fix in Beta 11.
