### ISSUE TITLE
BooleanValue isStopQueued () not working correctly

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#292]
ClipLauncherSlot.isStopQueued () does either report the same values as isPlaybackQueued() or nothing.

Furthermore, the JavaDoc is wrong:
"that reports whether this slot is queued for recording or not."

**Comment by abique** [comment]
I've adjusted the doc to:
> Value that reports true if the slot has a clip playing and the track is queued for stop.

I've also fixed the impl for the next major release.

**Comment by git-moss** [comment]
Fixed.
