### ISSUE TITLE
Add to insertCLAPDevice method to InsertionPoint 

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#296]
CLAP devices can currently not inserted.

**Comment by abique** [comment]
Fixed for next major release.

**Comment by git-moss** [comment]
Works fine.

One small issue: if I execute the "Copy Device Id to Clipboard" on a CLAP device in Bitwig, I get:

clap:com.u-he.MFM2:2.5.0

but the method only accepts:  com.u-he.MFM2

This should be harmonized (or accept different variations: with/without clap-prefix and/or version number).

Is there a use-case where multiple versions should be supported? Could make sense.
