### ISSUE TITLE
CursorDevice.addPositionObserver only receives 0 or -1

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#39]
When there is no device on the track it receives 0.
When there are devices on the track it always receives -1.

**Comment by vosc** [comment]
Bitwig Issue ID: FLOAT-7670
Fixed in 1.1.6 (not online yet)

**Comment by git-moss** [comment]
Close, but not yet there :-)
The first device does not report "0". 2nd, 3rd, ... devices work fine.

**Comment by git-moss** [comment]
Forget my last comment. Wrong logging. Works fine!
