### ISSUE TITLE
Update delayed when note is deleted via API

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#40]
The behaviour is that you get the update for the note deletion when you delete or insert another note.

To reproduce enter in the Push note sequencer 2 notes. After that delete both of them. The second will not turn off (but it is deleted in the clip). If you delete/insert another note the previous one turns off.

**Comment by vosc** [comment]
Bitwig Issue ID: FLOAT-7948
Fixed in 1.1.6 (not online yet)

**Comment by teotigraphix** [comment]
This will be nice. :)

**Comment by teotigraphix** [comment]
Fixed in 1.6 confirmed
