### ISSUE TITLE
Values for direct parameters are sent but no matching parameter exists

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#41]
In some situations values for 'On' and 'AMOUNT' are sent but no according direct parameter is in the current set.
To reproduce:
- Add a polysynth
- Deactivate the device
- Direct parameter for "on" is sent.
The Push script prints out such errors.
I noticed AMOUNT mostly when testing with layers.

**Comment by git-moss** [comment]
Also happens sometimes with full parameter sets:
- Create a couple of devices
- Switch between them

**Comment by git-moss** [comment]
Also happens when changing a send value in a layer:
Direct parameter 'AMOUNT' not found.

**Comment by vosc** [comment]
Should be fixed in 1.2-b2 (not released yet).

**Comment by git-moss** [comment]
Fixed in Beta 3.
