### ISSUE TITLE
De-/Activation of observers

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#43]
Registering observers (incl. datagramobservers) is only possible in the init function. In the init-function it is not guaranteed that the configuration properties are already correctly set because they fire asynchroneously. Therefore, the observer setup can not be dependent on properties.

This is e.g. a problem for the OSC script. The server IP property is not working because of this.

**Comment by vosc** [comment]
Datagram-observer case should be fixed in 1.1.6 (not released yet).

**Comment by git-moss** [comment]
How is it fixed? Can I now register outside the function? If this is the case I would also need to remove the old one if the user changes the IP in the settings.

**Comment by vosc** [comment]
Yes, you should be able to register outside of the init function now. But you are right, removing the old observer is necessary as well if the IP should be user configured.

**Comment by git-moss** [comment]
Closing this since the title is different than the content of this issue. The title issue is still in #19.
