### ISSUE TITLE
Find device of specific type on a track

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#44]
I'd like to find a drum instrument on a track to get required information for the drum view (solo/mute of instruments, etc.).
It seems that PrimaryDevice.addCanSwitchToDeviceObserver / switchToDevice is intended to do this but the available type is only ANY.
Furthermore, it seems that PrimaryDevice is deprecated. Is that the case because all functions who created it are deprecated?

**Comment by NickJAllen** [comment]
I think best is that we have a way to set some kind of DeviceMatcher on a DeviceBank so it only shows the devices matching the matcher. Colud create matchers for any instrument, fx, vst2 plugin etc

**Comment by NickJAllen** [comment]
APIs added in API version 12 which should be in 3.2.5
