### ISSUE TITLE
getSend of a drum pad always returns null

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#54]

**Comment by vosc** [comment]
Bitwig Issue ID: FLOAT-7673

**Comment by vosc** [comment]
Fixed in 1.1.6 RC1

**Comment by git-moss** [comment]
Can't see a difference to 1.1.6pre. Still broken.

**Comment by vosc** [comment]
Sorry forgot to mention, the createCursorDevice functions take an optional argument now that specifies the number of sends. By default it's zero, and in that case you would get null.

**Comment by git-moss** [comment]
I tested this again and it is working for instrument layers in 1.1.8 but not for drum pads:
this.cursorDevice = host.createEditorCursorDevice (this.numSends)
this.drumPadBank = this.cursorDevice.createDrumPadBank (this.numDrumPadLayers);
for (i = 0; i < this.numDeviceLayers; i++)
{
    layer = this.drumPadBank.getChannel (i);
    for (var j = 0; j < this.numSends; j++)
    {
        var s = layer.getSend (j);

--> s === null

**Comment by vosc** [comment]
should be fixed for drum pads as well in 1.2-b2 (not online yet).

**Comment by git-moss** [comment]
Fixed in Beta 2.
