### ISSUE TITLE
Problems with sibling device bank

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#55]
1) There is a function missing to select a device in the bank. Alternatively, if you want to keep it in sync with Tracks you could also add Device.selectInEditor().

2) To select the next (or previous) device I need to use cursorDevice.selectNext(). If I am on the 2nd page of the sibling bank (e.g. device 9, 10, ... is selected) and call this function the sibling bank is moved to the first page.

**Comment by git-moss** [comment]
Found a solution for 1):
    this.cursorDevice.selectDevice (this.siblings.getDevice (index));

**Comment by vosc** [comment]
Regarding 2)
you can call deviceBank.scrollTo(position), and pass in the position that you get reported by device.addPositionObserver...

**Comment by vosc** [comment]
Regarding 2) 
Bitwig Issue ID: FLOAT-7963 ... it's done for 1.1.6 RC1

**Comment by git-moss** [comment]
Can't see a difference to 1.1.6pre.

**Comment by vosc** [comment]
I added a more robust fix for RC2 (restore exact window offset instead of trying to make selected device visible in the bank).

**Comment by git-moss** [comment]
Works fine in 1.1.6RC2!
