### ISSUE TITLE
layerBank.scrollChannelsPageUp () does not work

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#56]
layerBank.scrollChannelsPageDown () seems to work fine.

**Comment by vosc** [comment]
Cannot reproduce, both scrollChannelsPageDown and scrollChannelsPageUp works fine for me, tested using Shift+Left/Right with Push script.

**Comment by git-moss** [comment]
I tested again, you are right it is working but the bug is another one. The two boolean values are flipped:
this.cursorDeviceLayer = this.cursorDevice.createCursorLayer ();
this.cursorDeviceLayer.addCanSelectPreviousObserver (     <- SENDS THE NEXT VALUE
this.cursorDeviceLayer.addCanSelectNextObserver (            <- SENDS THE PREVIOUS VALUE

**Comment by vosc** [comment]
I can't reproduce the flipped values, looks correct to me.

**Comment by git-moss** [comment]
If you tested with the Pushscript: I switched the values there, so it might have look OK for you.

**Comment by git-moss** [comment]
Works in 1.1.8.
