### ISSUE TITLE
CursorDevice.selectParent not working for when in a layer of a multiout VST

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#58]
You can test with the Push script:
- Add NI Kontakt to a track
- "Add missing chains"
- Add a plugin to one of the output layers
- Press Device button on push
- Enter Kontakt down to the plugin
- Now try to step up again...

**Comment by git-moss** [comment]
Seems to happen in 1.2 Beta 1 with all VSTs.

**Comment by vosc** [comment]
Should be fixed in 1.2-b2 (not online yet).

**Comment by git-moss** [comment]
Fixed in Beta 3.
