### ISSUE TITLE
Mixer needs toggle/observer for Show effect tracks and activate tracks

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/Framework4Bitwig#76]

**Comment by teotigraphix** [comment]
@vosc Any chance of these two little things in 1.2? (they are disabled right now)

![eatracks](https://cloud.githubusercontent.com/assets/226417/9640376/47f8cb96-517f-11e5-8338-b189fe228f2a.JPG)

**Comment by teotigraphix** [comment]
@vosc Ping! :)

**Comment by git-moss** [comment]
Arranger.areEffectTracksVisible () is availble since V1.
