### ISSUE TITLE
Device Browsing: Dialog only opens if a device is selected.

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#77]
Bitwig issue ID: FLOAT-9239

**Comment by vosc** [comment]
i can't reproduce this, please check in beta-6, might have been fixed along with other issues.
if you can still reproduce it, please add steps to reproduce (e.g. with push).

**Comment by git-moss** [comment]
I still can't make this work in Beta 7. To reproduce press "Add Effect" on the push. I am trying to activate a device browsing session. If no device is selected nothing happens. If a device is selected the browser opens but with the preset tab selected.
See the function "AbstractView.prototype.onAddEffect" in line 640 of AbstractViewExtensions.js. The relevant classes are BrowserProxy.js and BrowserSessionProxy.js.

**Comment by vosc** [comment]
Ok think i got it now. 
At the moment the browser can only be opened on existing devices via controller API. 
What you meant is that the JS device object needs to be actually connected to a device to make the device browser work, not that it appears selected in the user interface, right?

I think that would indeed be a nice improvement for inserting also new devices into a chain, just not sure yet if i would do it in the Device API or rather in the DeviceChain API.

**Comment by git-moss** [comment]
Yes, that's how I expected it to work since browsing devices is especially useful when adding a new one :-)
The documentation did also not note that it only works for existing devices.

**Comment by ThomasHelzle** [comment]
+1 to being able to create a new device after a given position in a chain. I would expect it in the device Chain API I think.
Cheers,
Tom

**Comment by git-moss** [comment]
Additionally, I would need to open the browser for samples/songs on clips.

**Comment by git-moss** [comment]
Implemented in v2.
