### ISSUE TITLE
Pressing the Down Arrow in the browser does not move the focus to the patches

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#78]
Til Beta 4 you could enter a search text and then press the down button to quickly jump to the patch column.

**Comment by vosc** [comment]
Are you sure about this one? It works fine for me (on OSX).

**Comment by git-moss** [comment]
Yes, but on Windows 10. Also checked with Beta 4 where it is still working fine.

**Comment by git-moss** [comment]
I found the problem: I created my own keymap with an older beta and it seems that the changes in the default map where not put into my map. 
BTW: How do you store now your own map in Beta 5?
