### ISSUE TITLE
Browser API: Order of items in hierarchical columns is a bit random

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#79]
I cannot understand the logic behind the ordering of these columns, I would expect them to be when all folders are open to be read from top to bottom of the column.

**Comment by vosc** [comment]
I would expect that too :) 
Didn't notice it during testing though, but maybe didn't watch the GUI carefully enough. 
Are you talking about the item banks or the cursor navigation?
Bitwig issue ID: FLOAT-9281

**Comment by git-moss** [comment]
I rechecked again and the problem is only with the Devices column, see the difference in the two images:

![img_20150824_214342](https://cloud.githubusercontent.com/assets/3090132/9460250/8afa74e8-4b04-11e5-9d87-b5ad34b196a7.jpg)
![img_20150824_214354](https://cloud.githubusercontent.com/assets/3090132/9460251/8b1b7e4a-4b04-11e5-8e3a-99166022c05d.jpg)

**Comment by git-moss** [comment]
Fixed in Beta 7.
