### ISSUE TITLE
Add option to createSiblingsTrackBank to hide effect tracks and master track

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#80]

**Comment by vosc** [comment]
Is it good enough to pass arguments such as "includeEffectTracks", "includeMasterTrack" on creation? 
Or do we need to have separate setting for nested tracks and top level tracks (see #84)?
Or does the configuration need to be changed at runtime (which i would like to avoid)?

**Comment by git-moss** [comment]
The two parameters would be fine for me.

**Comment by vosc** [comment]
ok, it's done for beta-8.

**Comment by git-moss** [comment]
I set both parameters to "false" but they still appear. Also set them to true to check if its swapped but they also appeared

**Comment by git-moss** [comment]
Fixed in Beta 9.
