### ISSUE TITLE
 trackBank.getChannel (index).selectInEditor () only selects tracks on the first page...

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#82]
... of the track bank. If a track on the second page is selected the track window is moved back to the first page.

**Comment by vosc** [comment]
looks like this is happening because the track position observer reports the wrong value, it needs to take the context into account (i.e. flat track list vs nested track list) ... i'll fix this for beta-6, could be that other bugs are caused by this as well.

**Comment by git-moss** [comment]
Fixed.
