### ISSUE TITLE
Siblings of channels in group must not contain the group itself

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#84]

**Comment by git-moss** [comment]
Still in Beta 7.

**Comment by vosc** [comment]
should be fixed in beta-8.

it was actually not the group itself, but it's master track, which got the same name as the group.
for now i only include the master track when we are in the top level track group.

#80 seems related.

**Comment by git-moss** [comment]
Closing this one since its the same as #80.
