### ISSUE TITLE
Master track is selected if specific group is selected

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#88]
@vosc: If I select the group "Melody" in the project "RumpingBeat" I sent you (to fix a previous crash) the master track is sent as the only channel of the siblings.
All other groups work fine.

**Comment by vosc** [comment]
i can't reproduce this, eventually was fixed together with other issues already. please try again in beta-8.

**Comment by git-moss** [comment]
Hmm, still have this.

**Comment by git-moss** [comment]
I ungrouped all tracks and regrouped them. Now it works, I guess this was a file-problem related to several beta updates.
