### ISSUE TITLE
Device navigation (previous/next) is broken

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#91]
Add some devices (e.g. Polysynth + Delay). Move from the first to the second. Cannot move back to the first. Direct selection is working.

**Comment by vosc** [comment]
ok, i could reproduce it, should be fixed in beta-8, thanks!

**Comment by teotigraphix** [comment]
Yeah I got that as well.

**Comment by git-moss** [comment]
Fixed.

**Comment by teotidev** [comment]
You are testing beta 8 moss?
