### ISSUE TITLE
Slots/Clips and Groups

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#92]
1) Slots do not signal that they have content, which means that the clip matrix looks empty (e.g. on Push, APC). They should send true if there is at least 1 clip on a sub-track.

2) Calling "select" on a slot enters the group but should only select it.

**Comment by git-moss** [comment]
1) Is not a bug, needs extension of the API

2) Still in 1.2.

**Comment by git-moss** [comment]
Still in 1.3 RC2

**Comment by lem8r** [comment]
3) calling `tracksBankView.getChannel().getClipLauncherSlots().createEmptyClip()` on a slot of group track is changing slot's icon like there is new clip inside the group. It should simply do nothing on a group channel.

**Comment by git-moss** [comment]
1) got fixed in 1.3.14.
2) is moved to https://github.com/teotigraphix/Framework4Bitwig/issues/122 for better visibility
