### ISSUE TITLE
Direct parameters can't be changed anymore

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#93]
Since Beta 10.

**Comment by git-moss** [comment]
Still in 1.2.

**Comment by vosc** [comment]
You mean calling setDirectParameterValueNormalized or incDirectParameterValueNormalized has no effect? I cannot reproduce that, works fine for me.

**Comment by git-moss** [comment]
Argh, seems I broke something when I fixed the maximum value problem. Need to research whats the difference to normal parameters...

**Comment by git-moss** [comment]
Had a closer look now. There is a conceptual problem here. All value setters (incl. setDirectParameterValueNormalized) require "integer number in the range [0 .. resolution-1] " as the value. But the addDirectParameterNormalizedValueObserver handler gets the value as a float from 0..1! When I put that in the setter I natuarally get 0. I scaled it up now to 0..127 but that works not perfectly due to rounding errors.
Maybe the correct solution would be to add the possibility to add a range parameter to the observer configuration.

**Comment by git-moss** [comment]
Side effects are that On/Off and other concrete parameters (e.g. Polysynth OSC octave) do not work.

**Comment by git-moss** [comment]
I scaled the range now up to 1000000000000 which makes it smooth. 
But I have no idea how to deal with parameters with non-continuous value range because I can not reach the next value.

**Comment by git-moss** [comment]
Still in 1.3.8 RC 2

**Comment by git-moss** [comment]
Closing this since I switch to incDirectParameterValueNormalized which works fine.
