### ISSUE TITLE
Plugins on group track are not shown as CursorDevice

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#97]
Got this report from a Push4Bitwig user yesterday. Just had a very quick look and it seems he's right. When you select a group track the info about plugins and the cursorplugin are not sent via the API.

**Comment by vosc** [comment]
Yes i could reproduce this too, should be fixed with the next update.

**Comment by git-moss** [comment]
Fixed in 1.3 RC2.
